Spacer/Spacer/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('groups/', include('groups.urls', namespace='groups')),
    path('posts/', include('posts.urls', namespace='posts')),
    re_path(r'^test/$', views.TestPage.as_view(), name='test'),
    re_path(r'^thanks/$', views.ThanksPage.as_view(), name='thanks'),
]

Spacer/groups/urls.py
from django.urls import path, re_path
from . import views

app_name = 'groups'

urlpatterns = [
    path('', views.ListGroups.as_view(), name='all'),
    path('new/', views.CreateGroup.as_view(), name='create'),
    re_path(r'^posts/in/(?P<slug>[-\w]+)/$', views.SingleGroup.as_view(), name='single'),
    re_path(r'^leave,/(?P<slug>[-\w]+)/$', views.LeaveGroup.as_view(), name='leave'),
    re_path(r'^join/(?P<slug>[-\w]+)/$', views.JoinGroup.as_view(), name='join')
]

Spacer/posts/urls.py
from django.urls import path, re_path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name='all'),
    path('new/', views.CreatePost.as_view(), name='create'),
    re_path(r'by/(?P<username>[-\w]+)/', views.UserPosts.as_view(), name='for_user'),
    re_path(r'by/(?P<username>[-\w]+)/(?P<pk>\d+)/$', views.PostDetail.as_view(), name='single'),
    re_path(r'delete/(?P<pk>\d+)/$', views.DeletePost.as_view(), name='delete')
]

Spacer/groups/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
from django.core.validators import validate_slug

# Create your models here.
import misaka

from django.contrib.auth import get_user_model
User = get_user_model()

from django import template
register = template.Library()

class Group(models.Model):
    name = models.CharField(max_length=100, unique=True, validators=[validate_slug])
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(max_length=500, blank=True, default='', validators=[validate_slug])
    description_html = models.TextField(max_length=500, editable=False, default='', blank=True, validators=[validate_slug])
    members = models.ManyToManyField(User, through='GroupMember')

    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)
    
    def get_absolute_url(self):
        return reverse('groups:single', kwargs={'slug':self.slug})
    
    class Meta:
        ordering = ['name']



class GroupMember(models.Model):
    group = models.ForeignKey(Group, related_name='memberships', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='user_groups', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username
    class Meta:
        unique_together = ('group', 'user')

Spacer/groups/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.shortcuts import get_object_or_404
from django.contrib import messages
from .models import Group, GroupMember
# Create your views here.
# GROUP VIEWS.PY

class CreateGroup(LoginRequiredMixin, generic.CreateView):
    fields = ('name', 'description')
    model = Group

class SingleGroup(generic.DetailView):
    model = Group

class ListGroups(generic.ListView):
    model = Group

class JoinGroup(LoginRequiredMixin, generic.RedirectView):
    
    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single', kwargs={'slug':self.kwargs.get('slug')})
    
    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group, slug=self.kwargs.get('slug'))

        try:
            GroupMember.objects.create(user=self.request.user, group=group)
        except:
            messages.warning(self.request, 'Warning already a member!')
        else:
            messages.success(self.request, 'You are now a member!')

        return super().get(request, *args, **kwargs)

class LeaveGroup(LoginRequiredMixin, generic.RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single', kwargs={'slug':self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        try:
            membership = GroupMember.objects.filter(
                user=self.request.user,
                group__slug=self.kwargs.get('slug')
            ).get()
        except GroupMember.DoesNotExist:
            messages.warning(self.request, 'Sorry you are not in this group!')
        else:
            membership.delete()
            messages.success(self.request, 'You have left the group!')
        return super().get(request, *args, **kwargs)

Spacer/groups/templates/groups/group_base.html
{% extends "base.html" %}
{% block body_block %}
<div class="container">


        {% block pregroup %}{% endblock %}
        {% block group_content %}{% endblock %}
        {% block postgroup %}{% endblock %}
</div>
{% endblock body_block %}

Spacer/groups/templates/groups/group_detail.html
{% extends "groups/group_base.html" %}



{% block pregroup %}

<h1>{{group.name}}</h1>
<hr>

<h4>Member Count: {{group.members.count}}</h4>
<hr>
<div class="row">
    <div class="content col-md-4">
        {% if user in group.members.all %}
        <a href="{% url 'groups:leave' slug=group.slug %}" class="btn btn-lg btn-fill btn-warning">Leave</a>
        {% else %}
        <a href="{% url 'groups:join' slug=group.slug %}" class="btn btn-lg btn-fill btn-success">Join</a>
        {% endif %}
    </div>

{% endblock %}



{% block group_content %}
    {% if group.posts.count == 0 %}
        <div class="col-md-8">
            <h4>No post in this group yet</h4>
        </div>
    {% else %}
    <div class="col-md-8">
        {% for post in group.posts.all %}
            {% include "posts/_post.html" %}
        {% endfor %}
    </div>
    {% endif %}
</div>


{% endblock %}

Spacer/groups/templates/groups/group_form.html
{% extends "groups/group_base.html" %}
{% load bootstrap4 %}

{% block pregroup %}
  <h4>Create a new group!</h4>
  <form action="{% url 'groups:create' %}" method='POST' id="groupForm">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" class="btn btn-primary btn-large" value="Create">
  </form>
{% endblock %}

Spacer/groups/templates/groups/group_list.html
{% extends "groups/group_base.html" %}

{% block pregroup %}
<div class="row">
    <div class="col-md-4">
        <div class="content">
            {% if user.is_authenticated %}
            <h2>Welcome Back!
                <a href="{% url 'posts:for_user' username=user.username %}">@{{user.username}}</a>
            </h2>
            {% endif %}
            <h2>Groups</h2>
            <p>Welcome to the groups page!</p>
        </div>
        {% if user.is_authenticated %}
        <a href="{% url 'groups:create' %}" class="btn btn-ld btn-fill btn-warning">Create Group</a>
        {% endif %}
    </div>

    <div class="col-md-8">
        {% for group in group_list %}
        <a href="{% url 'groups:single' slug=group.slug %}">
            <div class="card">
                <div class="card-header">
                    <h4>{{group.name|safe}}</h4>
                </div>
                <div class="card-body">
                    <blockquote class="blockquote mb-0">
                        <p>{{group.description_html|safe|truncatechars:200}}</p>
                    </blockquote>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <span class="badge badge-light">{{group.members.count}}</span>
                        member{{group.members.count|pluralize}}
                    </div>
                    <div class="col-sm-6">
                        <span class="badge badge-light">{{group.posts.count}}</span> post{{group.posts.count|pluralize}}
                    </div>
                </div>
            </div>
        </a>
        {% empty %}
        <p>No group was created!</p>

        {% endfor %}
    </div>
</div>
{% endblock %}